export enum RabbitServiceName {
  USER = 'USER_SERVICE',
  AUTH = 'AUTH_SERVICE',
  VEHICLE = 'VEHICLE_SERVICE',
  OTP = 'OTP_SERVICE',
  STORAGE = 'STORAGE_SERVICE',
  COMPANY = 'COMPANY_SERVICE',
  ORGANIZATION = 'ORGANIZATION_SERVICE',
  SERVICE = 'SERVICE_SERVICE',
  LOCATION = 'LOCATION_SERVICE',
  TURN = 'TURN_SERVICE',
  QUEUE = 'QUEUE_SERVICE',
  DEVICE = 'DEVICE_SERVICE',
}
